### ISSUE TITLE
Static Pages

### ISSUE THREAD

**Issue by loljoho** [roclin-grp/roclin-grp.github.io#15]
### Tasks

__Pages Directory__
 - [x] Move all static pages into `_pages/` directory
 - [x] Set `_config.yml`:
  ```yml
  include: ['_pages']
  ```

__Static Pages__
 - [x] #2 Landing Page
 - [x] #3 Contact Page
 - [x] #4 About Page
 - [x] #5 Terms of Service
 - [x] #6 Privacy Policy
 - [x] #17 Product Page
 - [x] #18 Pricing Page

__Includes Partials__
 - [x] `layout/hero-unit.html`
 - [x] `layout/card-group.html`
 - [x] `layout/card.html`
 - [ ] `layout/pagination.html`

### Links & Resources

 - https://bootstrapmade.com/demo/Green/
 - https://github.com/scotch-io/scotch-io.github.io
 - https://github.com/StackExchange/stack-blog
 - #26 Basic Layout Templates
 - #24 Page Content Data Files

**Comment by mavstronaut** [comment]
I remember being able to view some rough version of these static pages, but have peered into the branches to find that there are many 404's. 
Just getting familiar with the jekyll still. Will update later.
