### ISSUE TITLE
Change Asset Directories

### ISSUE THREAD

**Issue by loljoho** [roclin-grp/roclin-grp.github.io#32]
__Original File Structure__
```
assets/
├── 
│   ├── css
│   │   ├── ie10-viewport-bug-workaround.css
│   │   └── main.scss
│   ├── images
│   │   └── favicon
│   │       ├── android-chrome-192x192.png
│   │       ├── android-chrome-512x512.png
│   │       ├── apple-touch-icon.png
│   │       ├── browserconfig.xml
│   │       ├── favicon-16x16.png
│   │       ├── favicon-32x32.png
│   │       ├── favicon.ico
│   │       ├── manifest.json
│   │       ├── mstile-144x144.png
│   │       ├── mstile-150x150.png
│   │       ├── mstile-310x150.png
│   │       └── safari-pinned-tab.svg
│   └── js
│       ├── bootstrap.js
│       ├── bootstrap.min.js
│       ├── bootstrap-sprockets.js
│       ├── html5shiv.js
│       ├── html5shiv.min.js
│       ├── html5shiv-printshiv.js
│       ├── html5shiv-printshiv.min.js
│       ├── ie10-viewport-bug-workaround.js
│       ├── jquery-1.12.4.js
│       ├── jquery-1.12.4.min.js
│       ├── main.js
│       ├── respond.matchmedia.addListener.min.js
│       ├── respond.matchmedia.addListener.src.js
│       ├── respond.min.js
│       └── respond.src.js
```

__New File Structure__
```
├── css/
│   └── main.scss
│
├── js/
│   ├── bootstrap.js
│   ├── bootstrap.min.js
│   ├── bootstrap-sprockets.js
│   ├── html5shiv.js
│   ├── html5shiv.min.js
│   ├── html5shiv-printshiv.js
│   ├── html5shiv-printshiv.min.js
│   ├── ie10-viewport-bug-workaround.js
│   ├── jquery-1.12.4.js
│   ├── jquery-1.12.4.min.js
│   ├── main.js
│   ├── respond.matchmedia.addListener.min.js
│   ├── respond.matchmedia.addListener.src.js
│   ├── respond.min.js
│   └── respond.src.js
│
├── images/
│   └── favicon
│       ├── android-chrome-192x192.png
│       ├── android-chrome-512x512.png
│       ├── apple-touch-icon.png
│       ├── browserconfig.xml
│       ├── favicon-16x16.png
│       ├── favicon-32x32.png
│       ├── favicon.ico
│       ├── manifest.json
│       ├── mstile-144x144.png
│       ├── mstile-150x150.png
│       ├── mstile-310x150.png
│       └── safari-pinned-tab.svg
│
├── _sass/
│   ├── vendors/
│   │   └── ie10-viewport-bug-workaround.css
│   └── ...
```

### Task List ###

 - [x] Move `assets/css/` to `css/`
 - [x] Move `ie10-viewport-bug-workaround.css` to `_sass/vendors/`
 - [x] Move `assets/js/` to `js/`
 - [x] Move `assets/images/` to `images/`
 - [x] Edit paths in templates
   - [x] `_includes/head/assets.html`
   - [x] `_includes/head/meta.html`
   - [x] `_includes/body/scripts.html`
    ```html
    <link rel="stylesheet" href="{{ site.baseurl }}/css/main.css">
    <script src="{{ site.baseurl }}/css/main.js"></script>
    ```
