### ISSUE TITLE
Repository Organisation/Overhaul

### ISSUE THREAD

**Issue by loljoho** [roclin-grp/roclin-grp.github.io#45]
# Repository Organisation/Overhaul #45

## Task List ##

 - [ ] Create Template for Issues
 - [ ] Create Template for Pull Requests
 - [ ] Create Issue Labels
 - [ ] Organise Issues
   - [ ] Mark & Close Duplicate & Obsolete Issues
   - [ ] Appropriately Label Existing Issues
     - [ ] Issue Type
     - [ ] Issue Subtype
     - [ ] Severity Level (bugs)
     - [ ] Priority Level
     - [ ] Area Labels
     - [ ] Status Labels
   - [ ] Add Issue Cards to Project Board
     - [ ] Icebox
     - [ ] To Do
     - [ ] In Progress
     - [ ] Done
 - [ ] Create Project Milestones

<div align="right">
  <b><a href="#show_issue">⬆ back to top</a></b>
</div>

* * *

## <a id="_templates"></a>Issue & Pull Request Templates ##

1. Compose a clear, concise, and descriptive **Title**
   - Write with **proper English**: capitalisation, punctuation, etc.
   - Use the **present tense**
   - Good Examples:
     - Refactor responsive styles in Sass `layout/` partials
     - Update `README.md` legal disclaimer
     - Fix navbar social media link spacing
   - Bad Examples:
     - Landing Page
     - index carousel
     - Disqus Setup
2. Assign an appropriate **Type Label** to your issue
   - Each issue can only have **one** type label
3. Follow the instructions in the `ISSUE_TEMPLATE` carefully and in order
   - Some sections will be skipped based on your issue **Type**
   - Use **proper English**, including whole sentences and paragraphs where needed
   - Fill out any **lists or tables** if the template provides them for you

<div align="right">
  <b><a href="#show_issue">⬆ back to top</a></b>
</div>

* * *

## <a id="_links">Links & Resources ##

 - [Repository Guidelines · Issue #10 · roclin-grp/develop](https://github.com/roclin-grp/develop/issues/10)

<div align="right">
  <b><a href="#show_issue">⬆ back to top</a></b>
</div>

* * *

**Comment by loljoho** [comment]
# <a id="_issues"></a>Issues #

<!-- div class="toc-container" -->

<!-- div -->

## Table of Contents ##

<!-- div -->

* <a href="#_i01">#01 - Implement Assets Pipeline</a>
* <a href="#_i07">#07 - Content Editor</a>
* <a href="#_i08">#08 - CMS Admin GUI</a>
* <a href="#_i09">#09 - Deployment Automation</a>
* <a href="#_i10">#10 - RSS Feed</a>
* <a href="#_i11">#11 - Social Media Share</a>
* <a href="#_i17">#17 - Product Page</a>
* <a href="#_i18">#18 - Pricing Page</a>
* <a href="#_i19">#19 - Create Social Media Profiles</a>
* <a href="#_i23">#23 - Cards</a>
* <a href="#_i24">#24 - Page Content Data Files</a>
* <a href="#_i25">#25 - Implement jQuery.appear</a>
* <a href="#_i26">#26 - Basic Layout Templates</a>
* <a href="#_i28">#28 - Webpack Workflow Automation</a>
* <a href="#_i29">#29 - Page Content Collections</a>
* <a href="#_i30">#30 - SVG Partials</a>
* <a href="#_i31">#31 - Watch Task and Webpack</a>
* <a href="#_i35">#35 - Links & Assets Paths</a>
* <a href="#_i36">#36 - Browsersync</a>
* <a href="#_i37">#37 - Company Site</a>
* <a href="#_i39">#39 - index carousel</a>
* <a href="#_i42">#42 - Page Style Cleaning</a>
* <a href="#_i43">#43 - Update Carousel Images</a>
* <a href="#_i44">#44 - Updated Contact Form</a>
* <a href="#_i45">#45 - Repository Organisation/Overhaul</a>

<!-- /div -->

<div align="right">
  <b><a href="#show_issue">⬆ back to top</a></b>
</div>

* * *

<!-- /div -->

<!-- /div -->

<!-- div class="doc-container" -->

<!-- div -->

## Repository Issues ##

<!-- div -->

### <a id="_i01"></a>#01 - Implement Assets Pipeline ###
<a href="#_i01">#</a> · [&#x24C8;](https://github.com/roclin-grp/roclin-grp.github.io/issues/01) · Aug 1, 2017 · loljoho

#### Status ####
* Progress: unknown
* Priority: unknown

#### Scope ####
* Functional Area: unknown
* Functional Group: unknown

#### Notes ####
* Foo
* Bar

#### Links ####
* https://github.com/roclin-grp/roclin-grp.github.io/issues/01


<div align="right">
  <b><a href="#show_issue">⬆ back to top</a></b>
</div>

---

<!-- /div -->

<!-- div -->

### <a id="_i07"></a>#07 - Content Editor ###
<a href="#_i07">#</a> · [&#x24C8;](https://github.com/roclin-grp/roclin-grp.github.io/issues/07) · Aug 1, 2017 · loljoho

#### Status ####
* Progress: unknown
* Priority: unknown

#### Scope ####
* Functional Area: unknown
* Functional Group: unknown

#### Notes ####
* Foo
* Bar

#### Links ####
* https://github.com/roclin-grp/roclin-grp.github.io/issues/07


<div align="right">
  <b><a href="#show_issue">⬆ back to top</a></b>
</div>

---

<!-- /div -->

<!-- div -->

### <a id="_i08"></a>#08 - CMS Admin GUI ###
<a href="#_i08">#</a> · [&#x24C8;](https://github.com/roclin-grp/roclin-grp.github.io/issues/08) · Aug 1, 2017 · loljoho

#### Status ####
* Progress: unknown
* Priority: unknown

#### Scope ####
* Functional Area: unknown
* Functional Group: unknown

#### Notes ####
* Foo
* Bar

#### Links ####
* https://github.com/roclin-grp/roclin-grp.github.io/issues/08


<div align="right">
  <b><a href="#show_issue">⬆ back to top</a></b>
</div>

---

<!-- /div -->

<!-- div -->

### <a id="_i09"></a>#09 - Deployment Automation ###
<a href="#_i09">#</a> · [&#x24C8;](https://github.com/roclin-grp/roclin-grp.github.io/issues/9) · Aug 1, 2017 · loljoho

#### Status ####
* Progress: unknown
* Priority: unknown

#### Scope ####
* Functional Area: unknown
* Functional Group: unknown

#### Notes ####
* Foo
* Bar

#### Links ####
* https://github.com/roclin-grp/roclin-grp.github.io/issues/9


<div align="right">
  <b><a href="#show_issue">⬆ back to top</a></b>
</div>

---

<!-- /div -->

<!-- div -->

### <a id="_i10"></a>#10 - RSS Feed ###
<a href="#_i10">#</a> · [&#x24C8;](https://github.com/roclin-grp/roclin-grp.github.io/issues/10) · Aug 1, 2017 · loljoho

#### Status ####
* Progress: unknown
* Priority: unknown

#### Scope ####
* Functional Area: unknown
* Functional Group: unknown

#### Notes ####
* Foo
* Bar

#### Links ####
* https://github.com/roclin-grp/roclin-grp.github.io/issues/10


<div align="right">
  <b><a href="#show_issue">⬆ back to top</a></b>
</div>

---

<!-- /div -->

<!-- div -->

### <a id="_i11"></a>#11 - Social Media Share ###
<a href="#_i11">#</a> · [&#x24C8;](https://github.com/roclin-grp/roclin-grp.github.io/issues/11) · Aug 1, 2017 · loljoho

#### Status ####
* Progress: unknown
* Priority: unknown

#### Scope ####
* Functional Area: unknown
* Functional Group: unknown

#### Notes ####
* Foo
* Bar

#### Links ####
* https://github.com/roclin-grp/roclin-grp.github.io/issues/11


<div align="right">
  <b><a href="#show_issue">⬆ back to top</a></b>
</div>

---

<!-- /div -->

<!-- div -->

### <a id="_i17"></a>#17 - Product Page ###
<a href="#_i17">#</a> · [&#x24C8;](https://github.com/roclin-grp/roclin-grp.github.io/issues/17) · Aug 12, 2017 · loljoho

#### Status ####
* Progress: unknown
* Priority: unknown

#### Scope ####
* Functional Area: unknown
* Functional Group: unknown

#### Notes ####
* Foo
* Bar

#### Links ####
* https://github.com/roclin-grp/roclin-grp.github.io/issues/17


<div align="right">
  <b><a href="#show_issue">⬆ back to top</a></b>
</div>

---

<!-- /div -->

<!-- div -->

### <a id="_i18"></a>#18 - Pricing Page ###
<a href="#_i18">#</a> · [&#x24C8;](https://github.com/roclin-grp/roclin-grp.github.io/issues/18) · Aug 12, 2017 · loljoho

#### Status ####
* Progress: unknown
* Priority: unknown

#### Scope ####
* Functional Area: unknown
* Functional Group: unknown

#### Notes ####
* Foo
* Bar

#### Links ####
* https://github.com/roclin-grp/roclin-grp.github.io/issues/18


<div align="right">
  <b><a href="#show_issue">⬆ back to top</a></b>
</div>

---

<!-- /div -->

<!-- div -->

### <a id="_i19"></a>#19 - Create Social Media Profiles ###
<a href="#_i19">#</a> · [&#x24C8;](https://github.com/roclin-grp/roclin-grp.github.io/issues/19) · Aug 15, 2017 · loljoho

#### Status ####
* Progress: unknown
* Priority: unknown

#### Scope ####
* Functional Area: unknown
* Functional Group: unknown

#### Notes ####
* Foo
* Bar

#### Links ####
* https://github.com/roclin-grp/roclin-grp.github.io/issues/19


<div align="right">
  <b><a href="#show_issue">⬆ back to top</a></b>
</div>

---

<!-- /div -->

<!-- div -->

### <a id="_i23"></a>#23 - Cards ###
<a href="#_i23">#</a> · [&#x24C8;](https://github.com/roclin-grp/roclin-grp.github.io/issues/23) · Aug 15, 2017 · loljoho

#### Status ####
* Progress: unknown
* Priority: unknown

#### Scope ####
* Functional Area: unknown
* Functional Group: unknown

#### Notes ####
* Foo
* Bar

#### Links ####
* https://github.com/roclin-grp/roclin-grp.github.io/issues/23


<div align="right">
  <b><a href="#show_issue">⬆ back to top</a></b>
</div>

---

<!-- /div -->

<!-- div -->

### <a id="_i24"></a>#24 - Page Content Data Files ###
<a href="#_i24">#</a> · [&#x24C8;](https://github.com/roclin-grp/roclin-grp.github.io/issues/24) · Aug 15, 2017 · loljoho

#### Status ####
* Progress: unknown
* Priority: unknown

#### Scope ####
* Functional Area: unknown
* Functional Group: unknown

#### Notes ####
* Foo
* Bar

#### Links ####
* https://github.com/roclin-grp/roclin-grp.github.io/issues/24


<div align="right">
  <b><a href="#show_issue">⬆ back to top</a></b>
</div>

---

<!-- /div -->

<!-- div -->

### <a id="_i25"></a>#25 - Implement jQuery.appear ###
<a href="#_i25">#</a> · [&#x24C8;](https://github.com/roclin-grp/roclin-grp.github.io/issues/25) · Aug 15, 2017 · loljoho

#### Status ####
* Progress: unknown
* Priority: unknown

#### Scope ####
* Functional Area: unknown
* Functional Group: unknown

#### Notes ####
* Foo
* Bar

#### Links ####
* https://github.com/roclin-grp/roclin-grp.github.io/issues/25


<div align="right">
  <b><a href="#show_issue">⬆ back to top</a></b>
</div>

---

<!-- /div -->

<!-- div -->

### <a id="_i26"></a>#26 - Basic Layout Templates ###
<a href="#_i26">#</a> · [&#x24C8;](https://github.com/roclin-grp/roclin-grp.github.io/issues/26) · Aug 15, 2017 · loljoho

#### Status ####
* Progress: unknown
* Priority: unknown

#### Scope ####
* Functional Area: unknown
* Functional Group: unknown

#### Notes ####
* Foo
* Bar

#### Links ####
* https://github.com/roclin-grp/roclin-grp.github.io/issues/26


<div align="right">
  <b><a href="#show_issue">⬆ back to top</a></b>
</div>

---

<!-- /div -->

<!-- div -->

### <a id="_i28"></a>#28 - Webpack Workflow Automation ###
<a href="#_i28">#</a> · [&#x24C8;](https://github.com/roclin-grp/roclin-grp.github.io/issues/28) · Aug 16, 2017 · loljoho

#### Status ####
* Progress: unknown
* Priority: unknown

#### Scope ####
* Functional Area: unknown
* Functional Group: unknown

#### Notes ####
* Foo
* Bar

#### Links ####
* https://github.com/roclin-grp/roclin-grp.github.io/issues/28


<div align="right">
  <b><a href="#show_issue">⬆ back to top</a></b>
</div>

---

<!-- /div -->

<!-- div -->

### <a id="_i29"></a>#29 - Page Content Collections ###
<a href="#_i29">#</a> · [&#x24C8;](https://github.com/roclin-grp/roclin-grp.github.io/issues/29) · Aug 16, 2017 · loljoho

#### Status ####
* Progress: unknown
* Priority: unknown

#### Scope ####
* Functional Area: unknown
* Functional Group: unknown

#### Notes ####
* Foo
* Bar

#### Links ####
* https://github.com/roclin-grp/roclin-grp.github.io/issues/29


<div align="right">
  <b><a href="#show_issue">⬆ back to top</a></b>
</div>

---

<!-- /div -->

<!-- div -->

### <a id="_i30"></a>#30 - SVG Partials ###
<a href="#_i30">#</a> · [&#x24C8;](https://github.com/roclin-grp/roclin-grp.github.io/issues/30) · Aug 16, 2017 · loljoho

#### Status ####
* Progress: unknown
* Priority: unknown

#### Scope ####
* Functional Area: unknown
* Functional Group: unknown

#### Notes ####
* Foo
* Bar

#### Links ####
* https://github.com/roclin-grp/roclin-grp.github.io/issues/30


<div align="right">
  <b><a href="#show_issue">⬆ back to top</a></b>
</div>

---

<!-- /div -->

<!-- div -->

### <a id="_i31"></a>#31 - Watch Task and Webpack ###
<a href="#_i31">#</a> · [&#x24C8;](https://github.com/roclin-grp/roclin-grp.github.io/issues/31) · Aug 18, 2017 · loljoho

#### Status ####
* Progress: unknown
* Priority: unknown

#### Scope ####
* Functional Area: unknown
* Functional Group: unknown

#### Notes ####
* Foo
* Bar

#### Links ####
* https://github.com/roclin-grp/roclin-grp.github.io/issues/31


<div align="right">
  <b><a href="#show_issue">⬆ back to top</a></b>
</div>

---

<!-- /div -->

<!-- div -->

### <a id="_i35"></a>#35 - Links & Assets Paths ###
<a href="#_i35">#</a> · [&#x24C8;](https://github.com/roclin-grp/roclin-grp.github.io/issues/35) · Aug 23, 2017 · loljoho

#### Status ####
* Progress: unknown
* Priority: unknown

#### Scope ####
* Functional Area: unknown
* Functional Group: unknown

#### Notes ####
* Foo
* Bar

#### Links ####
* https://github.com/roclin-grp/roclin-grp.github.io/issues/35


<div align="right">
  <b><a href="#show_issue">⬆ back to top</a></b>
</div>

---

<!-- /div -->

<!-- div -->

### <a id="_i36"></a>#36 - Browsersync ###
<a href="#_i36">#</a> · [&#x24C8;](https://github.com/roclin-grp/roclin-grp.github.io/issues/36) · Aug 24, 2017 · loljoho

#### Status ####
* Progress: unknown
* Priority: unknown

#### Scope ####
* Functional Area: unknown
* Functional Group: unknown

#### Notes ####
* Foo
* Bar

#### Links ####
* https://github.com/roclin-grp/roclin-grp.github.io/issues/36


<div align="right">
  <b><a href="#show_issue">⬆ back to top</a></b>
</div>

---

<!-- /div -->

<!-- div -->

### <a id="_i37"></a>#37 - Company Site ###
<a href="#_i37">#</a> · [&#x24C8;](https://github.com/roclin-grp/roclin-grp.github.io/issues/37) · Sep 7, 2017 · mavstronaut

#### Status ####
* Progress: unknown
* Priority: unknown

#### Scope ####
* Functional Area: unknown
* Functional Group: unknown

#### Notes ####
* Foo
* Bar

#### Links ####
* https://github.com/roclin-grp/roclin-grp.github.io/issues/37


<div align="right">
  <b><a href="#show_issue">⬆ back to top</a></b>
</div>

---

<!-- /div -->

<!-- div -->
 
### <a id="_i39"></a>#39 - index carousel ###
<a href="#_i39">#</a> · [&#x24C8;](https://github.com/roclin-grp/roclin-grp.github.io/issues/39) · 28 days ago · mavstronaut

#### Status ####
* Progress: unknown
* Priority: unknown

#### Scope ####
* Functional Area: unknown
* Functional Group: unknown

#### Notes ####
* Foo
* Bar

#### Links ####
* https://github.com/roclin-grp/roclin-grp.github.io/issues/39


<div align="right">
  <b><a href="#show_issue">⬆ back to top</a></b>
</div>

---

<!-- /div -->

<!-- div -->

### <a id="_i42"></a>#42 - Page Style Cleaning ###
<a href="#_i42">#</a> · [&#x24C8;](https://github.com/roclin-grp/roclin-grp.github.io/issues/42) · 16 days ago · mavstronaut

#### Status ####
* Progress: unknown
* Priority: unknown

#### Scope ####
* Functional Area: unknown
* Functional Group: unknown

#### Notes ####
* Foo
* Bar

#### Links ####
* https://github.com/roclin-grp/roclin-grp.github.io/issues/42


<div align="right">
  <b><a href="#show_issue">⬆ back to top</a></b>
</div>

---

<!-- /div -->

<!-- div -->

### <a id="_i43"></a>#43 - Update Carousel Images ###
<a href="#_i43">#</a> · [&#x24C8;](https://github.com/roclin-grp/roclin-grp.github.io/issues/43) · 16 days ago · mavstronaut

#### Status ####
* Progress: unknown
* Priority: unknown

#### Scope ####
* Functional Area: unknown
* Functional Group: unknown

#### Notes ####
* Foo
* Bar

#### Links ####
* https://github.com/roclin-grp/roclin-grp.github.io/issues/43


<div align="right">
  <b><a href="#show_issue">⬆ back to top</a></b>
</div>

---

<!-- /div -->

<!-- div -->

### <a id="_i44"></a>#44 - Updated Contact Form ###
<a href="#_i44">#</a> · [&#x24C8;](https://github.com/roclin-grp/roclin-grp.github.io/issues/44) · 9 days ago · mavstronaut

#### Status ####
* Progress: unknown
* Priority: unknown

#### Scope ####
* Functional Area: unknown
* Functional Group: unknown

#### Notes ####
* Foo
* Bar

#### Links ####
* https://github.com/roclin-grp/roclin-grp.github.io/issues/44


<div align="right">
  <b><a href="#show_issue">⬆ back to top</a></b>
</div>

---

<!-- /div -->

<!-- div -->

### <a id="_i45"></a>#45 - Repository Organisation/Overhaul ###
<a href="#_i45">#</a> · [&#x24C8;](https://github.com/roclin-grp/roclin-grp.github.io/issues/45) · a day ago · loljoho

#### Status ####
* Progress: unknown
* Priority: unknown

#### Scope ####
* Functional Area: unknown
* Functional Group: unknown

#### Notes ####
* Foo
* Bar

#### Links ####
* https://github.com/roclin-grp/roclin-grp.github.io/issues/45


<div align="right">
  <b><a href="#show_issue">⬆ back to top</a></b>
</div>

---

<!-- /div -->

<div align="right">
  <b><a href="#show_issue">⬆ back to top</a></b>
</div>

* * *

<!-- /div -->

<!-- /div -->

**Comment by loljoho** [comment]
# <a id="_notes"></a>Notes #

Notes while resolving #41 Feat/39 index carousel and issue #39 index carousel 

## <a id="_notes-issues">Issues ##

Issues to create during #45

### Assets ###

 - [ ] Replace uncompressed `png` icons in `images/icons/` with icon font and/or `svg` files
 - [ ] Implement image compression for carousel images in `images/carousel/`
 - [ ] Replace `rlg-concept` files

### Pages ###

 - [ ] Refactor `index.md` layout template & partials
 - [ ] Refactor `blog.md` grid layout & components
 - [ ] Refactor `index.md` grid layout & components
 - [ ] Refactor `about.md` grid layout & components
 - [ ] Refactor `contact.md` grid layout & components
 - [ ] Refactor `blog.md` grid layout & components
 - [ ] Refactor `pricing.md` grid layout & components
 - [ ] Refactor `product.md` grid layout & components
 - [ ] Refactor `privacy.md` grid layout & components
 - [ ] Refactor `terms.md` grid layout & components

### Layout & Templating ###

 - [ ] Create splash screen
 - [ ] Create functioning contact form 
 - [ ] Refactor `page.html` layout template

### Blog & Blog Posts ###

 - [ ] Refactor `blog.html` layout template
   - [ ] Index of posts
   - [ ] Post excerpts
 - [ ] Refactor `post.html` layout template
   - [ ] Page Header
   - [ ] Post metadata
   - [ ] Share Post menu
   - [ ] Sidebar
     - [ ] Searchbar
     - [ ] Recent Posts
     - [ ] Categories
     - [ ] Tags
 - [ ] Create `category.html` layout template
 - [ ] Implement `categories` in Front Matter
 - [ ] Add Front Matter variables
   - [ ] `categories`
   - [ ] `tags`
   - [ ] `date`
 - [ ] Implement pagination

### Partials ###

 - [ ] Fix `navbar` navs
 - [ ] Fix `navbar` brand image
 - [ ] Add footer links for privacy, terms


### Content ###

 - [ ] Extract static page content into data files and collections
   - [ ] `about.md`
     - [ ] Team members
     - [ ] Collaborators
   - [ ] `contact.md`
 - [ ] Implement collections in static pages

### Tasks/Chores ###

 - [ ] Fix YAML Front Matter formatting in all files
 - [ ] Fix HTML and Liquid Template markup in all files
 - [ ] Fix and tidy up `_config.yml` 


<div align="right">
  <b><a href="#show_issue">⬆ back to top</a></b>
</div>

---
